apiVersion: v1
kind: Service
metadata:
  name: {{ template "carts-db.fullname" . }}
  labels:
    name: carts-db
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: carts-db